version: '3.8'
services:
  worker:
    build:
      context: ./worker
    image: esiea-ressources/worker

  vote:
    build:
      context: ./vote
    image: esiea-ressources/vote

  seed-data:
    build:
      context: ./seed-data
    image: esiea-ressources/seed-data

  result:
    build:
      context: ./result
    image: esiea-ressources/result
